name: Check for Spammy Issues

on:
  issue:
    types: [opened]

jobs:
  mark-as-spam:
    name: Remove issues with spammy
    runs-on: ubuntu-latest
    steps:
      - name: close issue
        uses: balevine/mark-as-spam@v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
